# Generated by Django 5.0.6 on 2025-01-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Select the department of the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='member',
            name='job_title',
            field=models.ForeignKey(blank=True, help_text='Select the job title of the employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.jobtitle', verbose_name='Job Title'),
        ),
    ]
