# Generated by Django 5.0.6 on 2025-01-24 13:14

import core.ledgers.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.ledgers.models.attachment_directory_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=150)),
                ('file_size', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_attachment', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Ledger_Attachment',
                'verbose_name_plural': 'Ledger_Attachments',
            },
        ),
        migrations.CreateModel(
            name='LedgerDoumentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.ledgers.models.letter_directory_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=150)),
                ('file_size', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_attachment', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Ledger_Dcoument_Attachment',
                'verbose_name_plural': 'Ledger_Document_Attachments',
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_email', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_person_first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_person_middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('ledger_subject', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('ledger_status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('ARCHIVED', 'ARCHIVED'), ('DELIVERED', 'DELIVERED'), ('IN_REVIEW', 'IN_REVIEW')], default='PENDING', max_length=200)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('written_at', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], max_length=200, null=True)),
                ('metadata_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata_fileType', models.CharField(blank=True, max_length=200, null=True)),
                ('metadata_confidentiality', models.CharField(blank=True, choices=[('PUBLIC', 'PUBLIC'), ('INTERNAL', 'INTERNAL'), ('CONFIDENTIAL', 'CONFIDENTIAL'), ('RESTRICTED', 'RESTRICTED')], max_length=200, null=True)),
                ('ledger_pdf', models.URLField(blank=True, null=True)),
                ('attachment', models.ManyToManyField(blank=True, to='ledgers.attachment')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.jobtitle')),
                ('letter', models.ManyToManyField(to='ledgers.ledgerdoumentattachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerSharing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ledger', to='ledgers.ledger')),
                ('shared_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ledger', 'shared_to')},
            },
        ),
    ]
