# Generated by Django 5.0.6 on 2024-12-29 20:31

import core.ledgers.models.attachment
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ledger_subject', models.CharField(max_length=200)),
                ('ledger_description', models.TextField(blank=True, null=True)),
                ('ledger_type', models.CharField(choices=[('INCOMING', 'Incoming'), ('OUTGOING', 'Outgoing'), ('PERSONAL', 'Personal')], default='INCOMING', max_length=200)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=200)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=200, null=True)),
                ('deadline', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('priority', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'LOW')], max_length=200, null=True)),
                ('ledger_pdf', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ledger',
                'verbose_name_plural': 'Ledger',
                'permissions': (('can_view_ledger', 'Can view ledger'), ('can_create_ledger', 'Can create ledger'), ('can_edit_ledger', 'Can edit ledger'), ('can_delete_ledger', 'Can delete ledger')),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.ledgers.models.attachment.attachment_directory_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=150)),
                ('file_size', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_attachment', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Ledger_Attachment',
                'verbose_name_plural': 'Ledger_Attachments',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_medium', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_channel', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_organization', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('expected_delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('STAMPED', 'Stamped'), ('DELIVERED', 'Delivered')], max_length=200, null=True)),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='ledgers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier_person_first_name', models.CharField(max_length=200)),
                ('carrier_person_middle_name', models.CharField(max_length=200)),
                ('carrier_person_last_name', models.CharField(max_length=200)),
                ('carrier_phone_number', models.PositiveIntegerField()),
                ('carrier_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization')], default='ORGANIZATION', max_length=200)),
                ('carrier_organization_id', models.CharField(blank=True, max_length=200, null=True)),
                ('carrier_plate_number', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrier', to='ledgers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LedgerDoumentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=core.ledgers.models.attachment.letter_directory_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=150)),
                ('file_size', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_attachment', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Ledger_Dcoument_Attachment',
                'verbose_name_plural': 'Ledger_Document_Attachments',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_owner', models.CharField(blank=True, max_length=200, null=True)),
                ('additional_message', models.CharField(blank=True, max_length=200, null=True)),
                ('document_type', models.CharField(choices=[('Letter', 'Letter'), ('Invoice', 'Invoice'), ('Receipt', 'Receipt'), ('Report', 'Report'), ('Other', 'Other')], default='Letter', max_length=200)),
                ('document_date', models.DateTimeField(blank=True, null=True)),
                ('external_reference_id', models.CharField(blank=True, max_length=200, null=True)),
                ('attachment', models.ManyToManyField(blank=True, to='ledgers.attachment')),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='ledgers.ledger')),
                ('letter', models.ManyToManyField(to='ledgers.ledgerdoumentattachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metaData_title', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_description', models.TextField(blank=True, null=True)),
                ('metaData_author', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_dateCreated', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_lastModified', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_category', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_fileType', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_language', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_status', models.CharField(choices=[('DRAFT', 'Draft'), ('INREVIEW', 'InReview'), ('InReview', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=200)),
                ('metaData_confidentiality', models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], default='INTERNAL', max_length=200)),
                ('metaData_version', models.CharField(blank=True, max_length=200, null=True)),
                ('metaData_source_system', models.CharField(blank=True, max_length=200, null=True)),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadatas', to='ledgers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('sector', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.department')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='departments.jobtitle')),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='ledgers.ledger')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
