# Generated by Django 5.0.6 on 2025-01-24 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgersharing',
            name='shared_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shared_by_ledgers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ledgersharing',
            name='shared_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_to_ledgers', to=settings.AUTH_USER_MODEL),
        ),
    ]
