# Generated by Django 5.0.6 on 2024-12-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_author',
            new_name='metadata_author',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_category',
            new_name='metadata_category',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_dateCreated',
            new_name='metadata_dateCreated',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_description',
            new_name='metadata_description',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_fileType',
            new_name='metadata_fileType',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_keywords',
            new_name='metadata_keywords',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_language',
            new_name='metadata_language',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_lastModified',
            new_name='metadata_lastModified',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_source_system',
            new_name='metadata_source_system',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_tags',
            new_name='metadata_tags',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_title',
            new_name='metadata_title',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metaData_version',
            new_name='metadata_version',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='metaData_confidentiality',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='metaData_status',
        ),
        migrations.AddField(
            model_name='metadata',
            name='metadata_confidentiality',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('CONFIDENTIAL', 'Confidential'), ('RESTRICTED', 'Restricted')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='metadata_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('INREVIEW', 'InReview'), ('InReview', 'Approved'), ('ARCHIVED', 'Archived')], max_length=200, null=True),
        ),
    ]
