# Generated by Django 5.0.6 on 2025-02-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_ledgersharing_shared_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='tracking_number',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
