# Generated by Django 5.0.6 on 2024-12-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0002_rename_metadata_author_metadata_metadata_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrier',
            options={'verbose_name': 'Carrier', 'verbose_name_plural': 'Carriers'},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Delivery', 'verbose_name_plural': 'Deliveries'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Ledger Document', 'verbose_name_plural': 'Ledger Documents'},
        ),
        migrations.AlterModelOptions(
            name='ledger',
            options={'permissions': (('can_view_ledger', 'Can view ledger'), ('can_create_ledger', 'Can create ledger'), ('can_edit_ledger', 'Can edit ledger'), ('can_delete_ledger', 'Can delete ledger')), 'verbose_name': 'Ledger', 'verbose_name_plural': 'Ledgers'},
        ),
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'Metadata', 'verbose_name_plural': 'Metadatas'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name': 'Recipient', 'verbose_name_plural': 'Recipients'},
        ),
    ]
