# Generated by Django 5.0.6 on 2024-12-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0003_alter_carrier_options_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='metadata_dateCreated',
            new_name='metadata_date_created',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metadata_fileType',
            new_name='metadata_file_type',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='metadata_lastModified',
            new_name='metadata_last_modified',
        ),
    ]
