# Generated by Django 5.0.6 on 2024-12-30 09:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0004_rename_metadata_datecreated_metadata_metadata_date_created_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_phone_number', models.PositiveIntegerField(blank=True, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('sender_address', models.CharField(blank=True, null=True)),
                ('sender_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ORGANIZATION', 'Organization')], default='ORGANIZATION', max_length=200)),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='ledgers.ledger')),
            ],
            options={
                'verbose_name': 'Sender',
                'verbose_name_plural': 'Senders',
            },
        ),
    ]
