# Generated by Django 5.0.6 on 2024-12-31 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0005_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrier',
            name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='tracking_number',
        ),
        migrations.AddField(
            model_name='ledger',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ledger_subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
