# Generated by Django 5.0.6 on 2024-12-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0006_remove_carrier_tracking_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='metadata_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('IN_REVIEW', 'In_Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived'), ('PUBLISHED', 'Published')], max_length=200, null=True),
        ),
    ]
