# Generated by Django 5.0.6 on 2024-12-31 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0007_alter_metadata_metadata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='carrier_phone_number',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sender',
            name='sender_phone_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
