# Generated by Django 5.0.6 on 2025-01-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0008_alter_carrier_carrier_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='sender_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
