# Generated by Django 5.0.6 on 2025-01-24 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0009_alter_sender_sender_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerSharing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ledger', to='ledgers.ledger')),
                ('shared_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ledger', 'shared_to')},
            },
        ),
    ]
