# Generated by Django 5.0.6 on 2025-01-24 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledgers', '0010_ledgersharing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgersharing',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ledger', to='ledgers.ledger'),
        ),
        migrations.AlterField(
            model_name='ledgersharing',
            name='shared_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_ledgers', to=settings.AUTH_USER_MODEL),
        ),
    ]
